In [22]:
import numpy as np
import matplotlib as plt
from sklearn import datasets

In [23]:
iris = datasets.load_iris()

In [24]:
X = iris.data
y = iris.target

In [25]:
X.shape

(150, 4)

In [26]:
y.shape

(150,)

In [27]:
#获取X(一个矩阵)的行数也就是样本数
len(X)

150

### train_test_split

尝试使用验证集，验证集的选取不能顺序取。y的排序是前50个是0型，下来50个是1型，最后50个是2型。
如果取前100个，则有可能取不到2型的标签，则预测时也不会预测出2型的鸢尾花
所以需要随机取样本，或者随机化样本的顺序
随机需要注意的是，样本和标签之前的对应关系不能改变。（很重要）
可以采用对索引随机选取的方式：

In [28]:
#在这个例子中，len(X)是150，permutation函数生成一个150个数，也就是从0到149的随机排列数组。返回值是array类型
shuffle_indexes = np.random.permutation(len(X))

In [29]:
shuffle_indexes

array([114, 137, 133,  85,  73,  83,   2, 107,  56, 142,   7,  67, 117,
         6, 111,  30, 109, 118,   4, 105, 116,  24,  34,  43,  87, 139,
        72,  31, 103,  15, 121, 119, 145, 113,  28,  60, 104,  39,  11,
        47, 143,  32,   1,   0,  35,  80, 136,  66,  90,  33,  57, 135,
        71, 138, 147,  53,  25,  54,  98,  82,  62,  77,  21,  27,  18,
       140, 149, 132,  84, 144,  17,  70, 131,  89,  88,  48,  20,  55,
        64,  44, 134,  79,  52,  51,  36,  76,  38,  22,   3,  23,  14,
        65, 130, 106, 125,  13, 148,  63,  45,  58,  75,  78, 112,  16,
        99,  92, 110, 141,   5,  49, 115,  26, 100, 127,   9, 124,  61,
       122,  86,  93,  12,  95,  46,  40,  81,  96,  10,  50,  19,  74,
        69,   8,  42, 101, 126, 129, 102, 120,  68, 108,  59,  97, 146,
        41, 128, 123,  37,  94,  29,  91])

In [30]:
test_ratio = 0.2
#通过设置比例的方式来确定测试集的数量，要注意结果可能不是整数，需要强制转换
test_size = int(test_ratio * len(X))

In [31]:
test_size

30

In [32]:
test_indexes = shuffle_indexes[:test_size] #前百分之二十是测试数据集
train_indexes = shuffle_indexes[test_size:]

In [33]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

### 使用我们的代码

In [34]:
from playML.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [36]:
from playML.KNN import KNNClassifier

In [37]:
my_knn_clf = KNNClassifier(k = 3)

In [38]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [39]:
X_test

array([[5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [5.1, 3.8, 1.5, 0.3],
       [5.1, 2.5, 3. , 1.1],
       [6.3, 2.5, 4.9, 1.5],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.8, 2.8, 4.8, 1.4],
       [4.4, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [4.5, 2.3, 1.3, 0.3],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.7, 3. , 5. , 1.7],
       [6.6, 3. , 4.4, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [6.1, 2.9, 4.7, 1.4],
       [4.4, 3. , 1.3, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.6, 1.4, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [6.7, 3. , 5.2, 2.3],
       [4.9, 2.4, 3.3, 1. ],
       [6.1, 2.8, 4.7, 1.2]])

In [42]:
y_predict = my_knn_clf.predict(X_test)

In [43]:
y_predict

array([1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 2,
       1, 0, 2, 0, 1, 2, 1, 1])

In [44]:
y_test

array([1, 1, 0, 1, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 0, 0, 0, 2,
       1, 0, 2, 0, 1, 2, 1, 1])

In [45]:
# sum()函数传入一个真值列表时，true为1，false为0
sum(y_predict == y_test)

28

In [46]:
sum(y_predict == y_test)/len(y_test)

0.9333333333333333